[package]
name = "ring-vrf"
version = "0.1.0"
description = "Ring VRF implementation using zkSNARKs."
authors = ["Sergey Vasilyev <swasilyev@gmail.com>", "Wei Tang <hi@that.world>"]
edition = "2018"
license = "MIT"

[dependencies]
ff = { git = "https://github.com/zcash/librustzcash" }
pairing = { git = "https://github.com/zcash/librustzcash" }
bellman = { git = "https://github.com/zcash/librustzcash" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash" }
rand_core = "0.5.1"

[dev-dependencies]
rand_xorshift = "0.2"
